# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1c41c7531bcf07fc1f3568535e40065350385dbb8000b5efef6ee5650863cc7f6c429bfd4ff8e9c3001f8a9ac55e5f2918f7a23b00cf3e592b3f310aec41d7

test:
  secret_key_base: 21a9f3a2385db67415362f0e1c3fd38729627f9233c18e19f12cf0befd2b023e66e7c58bf9376af760aa7e637d3465e8f412c45d8e534082766202a2efee79ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
